### PR TITLE
Add tracker results classes

### PR DESCRIPTION
**Pull request by AmraniCh**
## Changes

* Encapsulate tracker results into separate classes.
* New API methods introduced.
* Remove an import statement for an SPL exception class.
* Changing the unit tests to adopt the new features.

### CODE REVIEW

**Comment by peter279k** [comment]
It seems that the coding style is incorrect via the `PHP-CS-Fixer` checking.

Could you fix [that](https://github.com/peter279k/url-tracker/actions/runs/3474789606/jobs/5810435586)?

**Comment by AmraniCh** [comment]
It seems that the PSR-2 & PSR-12 standards are in conflict with one styling [rule](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/rules/function_notation/single_line_throw.rst) in Symfony Coding Standard.
However, PSR coding style standards do not require a hard limit on the line length limit, I think this is not really a problem so we can turn a blind eye.

**Comment by peter279k** [comment]
Thanks. The PSR-coding style seems to have the warnings now. I can resolve that after this PR is merged.

The static coding style checking is failed via the `phpstan` command running:

Could you check and fix that?

```sh
> phpstan analyse src tests --level=max -c phpstan.neon --no-progress --ansi
Error: Method Lee\Result\Result::jsonSerialize() return type has no value type specified in iterable type array.
Error: Method Lee\Result\Set::asArray() return type has no value type specified in iterable type array.
Error: Method Lee\Result\Set::asArray() should return array but returns mixed.
 ------ ----------------------------------------------------------------------- 
  Line   src/Result/Result.php                                                  
 ------ ----------------------------------------------------------------------- 
  40     Method Lee\Result\Result::jsonSerialize() return type has no value     
         type specified in iterable type array.                                 
         💡 See:                                                                 
         https://phpstan.org/blog/solving-phpstan-no-value-type-specified-in-i  
         terable-type                                                           
 ------ ----------------------------------------------------------------------- 

 ------ ----------------------------------------------------------------------- 
  Line   src/Result/Set.php                                                     
 ------ ----------------------------------------------------------------------- 
  20     Method Lee\Result\Set::asArray() return type has no value type         
         specified in iterable type array.                                      
         💡 See:                                                                 
         https://phpstan.org/blog/solving-phpstan-no-value-type-specified-in-i  
         terable-type                                                           
  27     Method Lee\Result\Set::asArray() should return array but returns       
         mixed.                                                                 
 ------ ----------------------------------------------------------------------- 

```

**Comment by peter279k** [comment]
It looks great for me. Merged and thanks!

**Pull request merged**
